// app/layout.tsx (or equivalent file)
import type { Metadata } from 'next';
import './globals.css';
import Navbar from './components/Layout/Navbar';
import ReduxProvider from './components/ReduxProvider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ReduxProvider>
          <Navbar />
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}